# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"%\n\x0fGetFilesRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"C\n\tFileChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x13\n\x0b\x65nd_of_file\x18\x03 \x01(\x08\x32G\n\x07Storage\x12<\n\x08GetFiles\x12\x18.storage.GetFilesRequest\x1a\x12.storage.FileChunk\"\x00\x30\x01\x62\x06proto3')



_GETFILESREQUEST = DESCRIPTOR.message_types_by_name['GetFilesRequest']
_FILECHUNK = DESCRIPTOR.message_types_by_name['FileChunk']
GetFilesRequest = _reflection.GeneratedProtocolMessageType('GetFilesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFILESREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:storage.GetFilesRequest)
  })
_sym_db.RegisterMessage(GetFilesRequest)

FileChunk = _reflection.GeneratedProtocolMessageType('FileChunk', (_message.Message,), {
  'DESCRIPTOR' : _FILECHUNK,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:storage.FileChunk)
  })
_sym_db.RegisterMessage(FileChunk)

_STORAGE = DESCRIPTOR.services_by_name['Storage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETFILESREQUEST._serialized_start=26
  _GETFILESREQUEST._serialized_end=63
  _FILECHUNK._serialized_start=65
  _FILECHUNK._serialized_end=132
  _STORAGE._serialized_start=134
  _STORAGE._serialized_end=205
# @@protoc_insertion_point(module_scope)
